spring:
  datasource:
    url: "jdbc:oracle:thin:@proyectossamanthadbdev_tp"
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${APP_USER}
    password: ${APP_PASSWORD}

    hikari:
      data-source-properties:
        oracle.net.tns_admin: "${WALLET_PATH}"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_schema: DEPLOY_USER

  liquibase:
    enabled: true
    url: "jdbc:oracle:thin:@proyectossamanthadbdev_tp"
    user: ${DEPLOY_USER}
    password: ${DEPLOY_PASSWORD}